# Generated by Django 4.2.5 on 2023-09-26 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skills",
            name="user",
        ),
        migrations.DeleteModel(
            name="Interest",
        ),
        migrations.DeleteModel(
            name="Skills",
        ),
    ]
