# Generated by Django 4.2.5 on 2023-09-26 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("profiles", "0004_remove_skills_user_delete_interest_delete_skills"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobHunterProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=15)),
                ("country", models.CharField(max_length=20)),
                ("city", models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name="education",
            name="user",
        ),
        migrations.RemoveField(
            model_name="experience",
            name="user",
        ),
        migrations.DeleteModel(
            name="Personal",
        ),
        migrations.AddField(
            model_name="jobhunterprofile",
            name="education",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="profiles.education"
            ),
        ),
        migrations.AddField(
            model_name="jobhunterprofile",
            name="experience",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="profiles.experience"
            ),
        ),
        migrations.AddField(
            model_name="jobhunterprofile",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
